language: node_js
node_js:
  - "10"
branches:
  only:
  - master
  - testnet
install:
  - npm install
script:
  - npm run data-service
  - npm run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "client.acrylplatform.com"
    skip_cleanup: true
    local_dir: dist/web/mainnet/min
    region: eu-central-1
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "clienttestnet.acrylplatform.com"
    skip_cleanup: true
    local_dir: dist/web/testnet/min
    region: eu-central-1
    on:
      branch: testnet
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "mobileclient.acrylplatform.com"
    skip_cleanup: true
    local_dir: dist/mobile_android/mainnet/min
    region: eu-central-1
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: "mobileclienttestnet.acrylplatform.com"
    skip_cleanup: true
    local_dir: dist/mobile_android/testnet/min
    region: eu-central-1
    on:
      branch: testnet
