(function () {
    'use strict';

    /**
     * @param Base
     * @returns {ChangeCountry}
     */
    const controller = function (Base) {

        class ChangeCountry extends Base {

            constructor() {
                super();
                /**
                 * @type {function}
                 */
                this.onChange = null;
                this.language = null;
                /**
                 * @type {string[]}
                 */
                this.enList = [
                    { code: 'Australia', name: 'Australia' },
                    { code: 'Austria', name: 'Austria' },
                    { code: 'Azerbaijan', name: 'Azerbaijan' },
                    { code: 'Albania', name: 'Albania' },
                    { code: 'Algeria', name: 'Algeria' },
                    { code: 'Angola', name: 'Angola' },
                    { code: 'Andorra', name: 'Andorra' },
                    { code: 'Antigua-and-Barbuda', name: 'Antigua-and-Barbuda' },
                    { code: 'Argentina', name: 'Argentina' },
                    { code: 'Armenia', name: 'Armenia' },
                    { code: 'Afghanistan', name: 'Afghanistan' },
                    { code: 'Bahamas', name: 'Bahamas' },
                    { code: 'Bangladesh', name: 'Bangladesh' },
                    { code: 'Barbados', name: 'Barbados' },
                    { code: 'Bahrain', name: 'Bahrain' },
                    { code: 'Belarus', name: 'Belarus' },
                    { code: 'Belize', name: 'Belize' },
                    { code: 'Belgium', name: 'Belgium' },
                    { code: 'Benin', name: 'Benin' },
                    { code: 'Bulgaria', name: 'Bulgaria' },
                    { code: 'Bolivia', name: 'Bolivia' },
                    { code: 'Bosnia-and-Herzegovina', name: 'Bosnia-and-Herzegovina' },
                    { code: 'Botswana', name: 'Botswana' },
                    { code: 'Brazil', name: 'Brazil' },
                    { code: 'Brunei', name: 'Brunei' },
                    { code: 'Burkina', name: 'Burkina' },
                    { code: 'Burundi', name: 'Burundi' },
                    { code: 'Butane', name: 'Butane' },
                    { code: 'Vanuatu', name: 'Vanuatu' },
                    { code: 'Great-Britain', name: 'Great-Britain' },
                    { code: 'Hungary', name: 'Hungary' },
                    { code: 'Venezuela', name: 'Venezuela' },
                    { code: 'East-Timor', name: 'East-Timor' },
                    { code: 'Vietnam', name: 'Vietnam' },
                    { code: 'Gabon', name: 'Gabon' },
                    { code: 'Haiti', name: 'Haiti' },
                    { code: 'Guyana', name: 'Guyana' },
                    { code: 'Gambia', name: 'Gambia' },
                    { code: 'Ghana', name: 'Ghana' },
                    { code: 'Guatemala', name: 'Guatemala' },
                    { code: 'Guinea', name: 'Guinea' },
                    { code: 'Guinea', name: 'Guinea' },
                    { code: 'Germany', name: 'Germany' },
                    { code: 'Honduras', name: 'Honduras' },
                    { code: 'Grenada', name: 'Grenada' },
                    { code: 'Greece', name: 'Greece' },
                    { code: 'Georgia', name: 'Georgia' },
                    { code: 'Denmark', name: 'Denmark' },
                    { code: 'Djibouti', name: 'Djibouti' },
                    { code: 'Dominica', name: 'Dominica' },
                    { code: 'Dominican-Republic', name: 'Dominican-Republic' },
                    { code: 'Egypt', name: 'Egypt' },
                    { code: 'Zambia', name: 'Zambia' },
                    { code: 'Zimbabwe', name: 'Zimbabwe' },
                    { code: 'Israel', name: 'Israel' },
                    { code: 'India', name: 'India' },
                    { code: 'Indonesia', name: 'Indonesia' },
                    { code: 'Jordan', name: 'Jordan' },
                    { code: 'Iraq', name: 'Iraq' },
                    { code: 'Iran', name: 'Iran' },
                    { code: 'Ireland', name: 'Ireland' },
                    { code: 'Iceland', name: 'Iceland' },
                    { code: 'Spain', name: 'Spain' },
                    { code: 'Italy', name: 'Italy' },
                    { code: 'Yemen', name: 'Yemen' },
                    { code: 'Cape', name: 'Cape' },
                    { code: 'Kazakhstan', name: 'Kazakhstan' },
                    { code: 'Cambodia', name: 'Cambodia' },
                    { code: 'Cameroon', name: 'Cameroon' },
                    { code: 'Canada', name: 'Canada' },
                    { code: 'Qatar', name: 'Qatar' },
                    { code: 'Kenya', name: 'Kenya' },
                    { code: 'Cyprus', name: 'Cyprus' },
                    { code: 'Kyrgyzstan', name: 'Kyrgyzstan' },
                    { code: 'Kiribati', name: 'Kiribati' },
                    { code: 'China', name: 'China' },
                    { code: 'Colombia', name: 'Colombia' },
                    { code: 'Comoros', name: 'Comoros' },
                    { code: 'Republic-of-the-Congo', name: 'Republic-of-the-Congo' },
                    { code: 'Democratic-Republic-of-the-Congo', name: 'Democratic-Republic-of-the-Congo' },
                    { code: 'North-Korea', name: 'North-Korea' },
                    { code: 'The-Republic-of-Korea', name: 'The-Republic-of-Korea' },
                    { code: 'Costa-Rica', name: 'Costa-Rica' },
                    { code: 'Côte-d-Ivoire', name: 'Côte-d-Ivoire' },
                    { code: 'Cuba', name: 'Cuba' },
                    { code: 'Kuwait', name: 'Kuwait' },
                    { code: 'Laos', name: 'Laos' },
                    { code: 'Latvia', name: 'Latvia' },
                    { code: 'Lesotho', name: 'Lesotho' },
                    { code: 'Liberia', name: 'Liberia' },
                    { code: 'Lebanon', name: 'Lebanon' },
                    { code: 'Libya', name: 'Libya' },
                    { code: 'Lithuania', name: 'Lithuania' },
                    { code: 'Liechtenstein', name: 'Liechtenstein' },
                    { code: 'Luxembourg', name: 'Luxembourg' },
                    { code: 'Mauritius', name: 'Mauritius' },
                    { code: 'Mauritania', name: 'Mauritania' },
                    { code: 'Madagascar', name: 'Madagascar' },
                    { code: 'Malawi', name: 'Malawi' },
                    { code: 'Malaysia', name: 'Malaysia' },
                    { code: 'Mali', name: 'Mali' },
                    { code: 'Maldives', name: 'Maldives' },
                    { code: 'Malta', name: 'Malta' },
                    { code: 'Morocco', name: 'Morocco' },
                    { code: 'Marshall-Islands', name: 'Marshall-Islands' },
                    { code: 'Mexico', name: 'Mexico' },
                    { code: 'Mozambique', name: 'Mozambique' },
                    { code: 'Moldavia', name: 'Moldavia' },
                    { code: 'Monaco', name: 'Monaco' },
                    { code: 'Mongolia', name: 'Mongolia' },
                    { code: 'Myanmar', name: 'Myanmar' },
                    { code: 'Namibia', name: 'Namibia' },
                    { code: 'Nauru', name: 'Nauru' },
                    { code: 'Nepal', name: 'Nepal' },
                    { code: 'Niger', name: 'Niger' },
                    { code: 'Nigeria', name: 'Nigeria' },
                    { code: 'Netherlands', name: 'Netherlands' },
                    { code: 'Nicaragua', name: 'Nicaragua' },
                    { code: 'New-Zealand', name: 'New-Zealand' },
                    { code: 'Norway', name: 'Norway' },
                    { code: 'United-Arab-Emirates', name: 'United-Arab-Emirates' },
                    { code: 'Oman', name: 'Oman' },
                    { code: 'Pakistan', name: 'Pakistan' },
                    { code: 'Palau', name: 'Palau' },
                    { code: 'Panama', name: 'Panama' },
                    { code: 'Papua-New-Guinea', name: 'Papua-New-Guinea' },
                    { code: 'Paraguay', name: 'Paraguay' },
                    { code: 'Peru', name: 'Peru' },
                    { code: 'Poland', name: 'Poland' },
                    { code: 'Portugal', name: 'Portugal' },
                    { code: 'Russia', name: 'Russia' },
                    { code: 'Rwanda', name: 'Rwanda' },
                    { code: 'Romania', name: 'Romania' },
                    { code: 'Salvador', name: 'Salvador' },
                    { code: 'Samoa', name: 'Samoa' },
                    { code: 'Sao-Tome-and-Principe', name: 'Sao-Tome-and-Principe' },
                    { code: 'San-Marino', name: 'San-Marino' },
                    { code: 'Saudi-Arabia', name: 'Saudi-Arabia' },
                    { code: 'North-Macedonia', name: 'North-Macedonia' },
                    { code: 'Seychelles', name: 'Seychelles' },
                    { code: 'Senegal', name: 'Senegal' },
                    { code: 'Vc', name: 'Vc' },
                    { code: 'Saint-Kitts-and-Nevis', name: 'Saint-Kitts-and-Nevis' },
                    { code: 'Saint-Lucia', name: 'Saint-Lucia' },
                    { code: 'Serbia', name: 'Serbia' },
                    { code: 'Singapore', name: 'Singapore' },
                    { code: 'Syria', name: 'Syria' },
                    { code: 'Slovakia', name: 'Slovakia' },
                    { code: 'Slovenia', name: 'Slovenia' },
                    { code: 'USA', name: 'USA' },
                    { code: 'Solomon-islands', name: 'Solomon-islands' },
                    { code: 'Somalia', name: 'Somalia' },
                    { code: 'Sudan', name: 'Sudan' },
                    { code: 'Surinam', name: 'Surinam' },
                    { code: 'Sierra-Leone', name: 'Sierra-Leone' },
                    { code: 'Tajikistan', name: 'Tajikistan' },
                    { code: 'Thailand', name: 'Thailand' },
                    { code: 'Tanzania', name: 'Tanzania' },
                    { code: 'Togo', name: 'Togo' },
                    { code: 'Tonga', name: 'Tonga' },
                    { code: 'Trinidad-and-Tobago', name: 'Trinidad-and-Tobago' },
                    { code: 'Tuvalu', name: 'Tuvalu' },
                    { code: 'Tunisia', name: 'Tunisia' },
                    { code: 'Turkmenistan', name: 'Turkmenistan' },
                    { code: 'Turkey', name: 'Turkey' },
                    { code: 'Uganda', name: 'Uganda' },
                    { code: 'Uzbekistan', name: 'Uzbekistan' },
                    { code: 'Ukraine', name: 'Ukraine' },
                    { code: 'Uruguay', name: 'Uruguay' },
                    { code: 'Federated-States-of-Micronesia', name: 'Federated-States-of-Micronesia' },
                    { code: 'Fiji', name: 'Fiji' },
                    { code: 'Philippines', name: 'Philippines' },
                    { code: 'Finland', name: 'Finland' },
                    { code: 'France', name: 'France' },
                    { code: 'Croatia', name: 'Croatia' },
                    { code: 'Central-African-Republic', name: 'Central-African-Republic' },
                    { code: 'Chad', name: 'Chad' },
                    { code: 'Montenegro', name: 'Montenegro' },
                    { code: 'Czech', name: 'Czech' },
                    { code: 'Chile', name: 'Chile' },
                    { code: 'Switzerland', name: 'Switzerland' },
                    { code: 'Sweden', name: 'Sweden' },
                    { code: 'Sri-Lanka', name: 'Sri-Lanka' },
                    { code: 'Ecuador', name: 'Ecuador' },
                    { code: 'Equatorial-Guinea', name: 'Equatorial-Guinea' },
                    { code: 'Eritrea', name: 'Eritrea' },
                    { code: 'Esvatini', name: 'Esvatini' },
                    { code: 'Estonia', name: 'Estonia' },
                    { code: 'Ethiopia', name: 'Ethiopia' },
                    { code: 'South-Africa', name: 'South-Africa' },
                    { code: 'South-Sudan', name: 'South-Sudan' },
                    { code: 'Jamaica', name: 'Jamaica' },
                    { code: 'Japan', name: 'Japan' }
                ];

                this.ruList = [
                    { code: 'Australia', name: 'Австралия' },
                    { code: 'Austria', name: 'Австрия' },
                    { code: 'Azerbaijan', name: 'Азербайджан' },
                    { code: 'Albania', name: 'Албания' },
                    { code: 'Algeria', name: 'Алжир' },
                    { code: 'Angola', name: 'Ангола' },
                    { code: 'Andorra', name: 'Андорра' },
                    { code: 'Antigua-and-Barbuda', name: 'Антигуа и Барбуда' },
                    { code: 'Argentina', name: 'Аргентина' },
                    { code: 'Armenia', name: 'Армения' },
                    { code: 'Afghanistan', name: 'Афганистан' },
                    { code: 'Bahamas', name: 'Багамские Острова' },
                    { code: 'Bangladesh', name: 'Бангладеш' },
                    { code: 'Barbados', name: 'Барбадос' },
                    { code: 'Bahrain', name: 'Бахрейн' },
                    { code: 'Belarus', name: 'Белоруссия' },
                    { code: 'Belize', name: 'Белиз' },
                    { code: 'Belgium', name: 'Бельгия' },
                    { code: 'Benin', name: 'Бенин' },
                    { code: 'Bulgaria', name: 'Болгария' },
                    { code: 'Bolivia', name: 'Боливия' },
                    { code: 'Bosnia-and-Herzegovina', name: 'Босния и Герцеговина' },
                    { code: 'Botswana', name: 'Ботсвана' },
                    { code: 'Brazil', name: 'Бразилия' },
                    { code: 'Brunei', name: 'Бруней' },
                    { code: 'Burkina', name: 'Буркина' },
                    { code: 'Burundi', name: 'Бурунди' },
                    { code: 'Butane', name: 'Бутан' },
                    { code: 'Vanuatu', name: 'Вануату' },
                    { code: 'Great-Britain', name: 'Великобритания' },
                    { code: 'Hungary', name: 'Венгрия' },
                    { code: 'Venezuela', name: 'Венесуэла' },
                    { code: 'East-Timor', name: 'Восточный Тимор' },
                    { code: 'Vietnam', name: 'Вьетнам' },
                    { code: 'Gabon', name: 'Габон' },
                    { code: 'Haiti', name: 'Гаити' },
                    { code: 'Guyana', name: 'Гайана' },
                    { code: 'Gambia', name: 'Гамбия' },
                    { code: 'Ghana', name: 'Гана' },
                    { code: 'Guatemala', name: 'Гватемала' },
                    { code: 'Guinea', name: 'Гвинея' },
                    { code: 'Guinea', name: 'Гвинея' },
                    { code: 'Germany', name: 'Германия' },
                    { code: 'Honduras', name: 'Гондурас' },
                    { code: 'Grenada', name: 'Гренада' },
                    { code: 'Greece', name: 'Греция' },
                    { code: 'Georgia', name: 'Грузия' },
                    { code: 'Denmark', name: 'Дания' },
                    { code: 'Djibouti', name: 'Джибути' },
                    { code: 'Dominica', name: 'Доминика' },
                    { code: 'Dominican-Republic', name: 'Доминиканская Республика' },
                    { code: 'Egypt', name: 'Египет' },
                    { code: 'Zambia', name: 'Замбия' },
                    { code: 'Zimbabwe', name: 'Зимбабве' },
                    { code: 'Israel', name: 'Израиль' },
                    { code: 'India', name: 'Индия' },
                    { code: 'Indonesia', name: 'Индонезия' },
                    { code: 'Jordan', name: 'Иордания' },
                    { code: 'Iraq', name: 'Ирак' },
                    { code: 'Iran', name: 'Иран' },
                    { code: 'Ireland', name: 'Ирландия' },
                    { code: 'Iceland', name: 'Исландия' },
                    { code: 'Spain', name: 'Испания' },
                    { code: 'Italy', name: 'Италия' },
                    { code: 'Yemen', name: 'Йемен' },
                    { code: 'Cape', name: 'Кабо' },
                    { code: 'Kazakhstan', name: 'Казахстан' },
                    { code: 'Cambodia', name: 'Камбоджа' },
                    { code: 'Cameroon', name: 'Камерун' },
                    { code: 'Canada', name: 'Канада' },
                    { code: 'Qatar', name: 'Катар' },
                    { code: 'Kenya', name: 'Кения' },
                    { code: 'Cyprus', name: 'Кипр' },
                    { code: 'Kyrgyzstan', name: 'Киргизия' },
                    { code: 'Kiribati', name: 'Кирибати' },
                    { code: 'China', name: 'Китай' },
                    { code: 'Colombia', name: 'Колумбия' },
                    { code: 'Comoros', name: 'Коморы' },
                    { code: 'Republic-of-the-Congo', name: 'Республика Конго' },
                    { code: 'Democratic-Republic-of-the-Congo', name: 'Демократическая Республика Конго' },
                    { code: 'North-Korea', name: 'КНДР' },
                    { code: 'The-Republic-of-Korea', name: 'Республика Корея' },
                    { code: 'Costa-Rica', name: 'Коста-Рика' },
                    { code: 'Côte-d-Ivoire', name: 'Кот-д-Ивуар' },
                    { code: 'Cuba', name: 'Куба' },
                    { code: 'Kuwait', name: 'Кувейт' },
                    { code: 'Laos', name: 'Лаос' },
                    { code: 'Latvia', name: 'Латвия' },
                    { code: 'Lesotho', name: 'Лесото' },
                    { code: 'Liberia', name: 'Либерия' },
                    { code: 'Lebanon', name: 'Ливан' },
                    { code: 'Libya', name: 'Ливия' },
                    { code: 'Lithuania', name: 'Литва' },
                    { code: 'Liechtenstein', name: 'Лихтенштейн' },
                    { code: 'Luxembourg', name: 'Люксембург' },
                    { code: 'Mauritius', name: 'Маврикий' },
                    { code: 'Mauritania', name: 'Мавритания' },
                    { code: 'Madagascar', name: 'Мадагаскар' },
                    { code: 'Malawi', name: 'Малави' },
                    { code: 'Malaysia', name: 'Малайзия' },
                    { code: 'Mali', name: 'Мали' },
                    { code: 'Maldives', name: 'Мальдивы' },
                    { code: 'Malta', name: 'Мальта' },
                    { code: 'Morocco', name: 'Марокко' },
                    { code: 'Marshall-Islands', name: 'Маршалловы Острова' },
                    { code: 'Mexico', name: 'Мексика' },
                    { code: 'Mozambique', name: 'Мозамбик' },
                    { code: 'Moldavia', name: 'Молдавия' },
                    { code: 'Monaco', name: 'Монако' },
                    { code: 'Mongolia', name: 'Монголия' },
                    { code: 'Myanmar', name: 'Мьянма' },
                    { code: 'Namibia', name: 'Намибия' },
                    { code: 'Nauru', name: 'Науру' },
                    { code: 'Nepal', name: 'Непал' },
                    { code: 'Niger', name: 'Нигер' },
                    { code: 'Nigeria', name: 'Нигерия' },
                    { code: 'Netherlands', name: 'Нидерланды' },
                    { code: 'Nicaragua', name: 'Никарагуа' },
                    { code: 'New-Zealand', name: 'Новая Зеландия' },
                    { code: 'Norway', name: 'Норвегия' },
                    { code: 'United-Arab-Emirates', name: 'ОАЭ' },
                    { code: 'Oman', name: 'Оман' },
                    { code: 'Pakistan', name: 'Пакистан' },
                    { code: 'Palau', name: 'Палау' },
                    { code: 'Panama', name: 'Панама' },
                    { code: 'Papua-New-Guinea', name: 'Папуа-Новая Гвинея ' },
                    { code: 'Paraguay', name: 'Парагвай' },
                    { code: 'Peru', name: 'Перу' },
                    { code: 'Poland', name: 'Польша' },
                    { code: 'Portugal', name: 'Португалия' },
                    { code: 'Russia', name: 'Россия' },
                    { code: 'Rwanda', name: 'Руанда' },
                    { code: 'Romania', name: 'Румыния' },
                    { code: 'Salvador', name: 'Сальвадор' },
                    { code: 'Samoa', name: 'Самоа' },
                    { code: 'Sao-Tome-and-Principe', name: 'Сан-Томе и Принсипи' },
                    { code: 'San-Marino', name: 'Сан-Марино ' },
                    { code: 'Saudi-Arabia', name: 'Саудовская Аравия' },
                    { code: 'North-Macedonia', name: 'Северная Македония' },
                    { code: 'Seychelles', name: 'Сейшельские Острова' },
                    { code: 'Senegal', name: 'Сенегал' },
                    { code: 'Vc', name: 'Сент-Винсент и Гренадины' },
                    { code: 'Saint-Kitts-and-Nevis', name: 'Сент-Китс и Невис ' },
                    { code: 'Saint-Lucia', name: 'Сент-Люсия' },
                    { code: 'Serbia', name: 'Сербия' },
                    { code: 'Singapore', name: 'Сингапур' },
                    { code: 'Syria', name: 'Сирия' },
                    { code: 'Slovakia', name: 'Словакия' },
                    { code: 'Slovenia', name: 'Словения' },
                    { code: 'USA', name: 'США' },
                    { code: 'Solomon-islands', name: 'Соломоновы Острова' },
                    { code: 'Somalia', name: 'Сомали' },
                    { code: 'Sudan', name: 'Судан' },
                    { code: 'Surinam', name: 'Суринам' },
                    { code: 'Sierra-Leone', name: 'Сьерра-Леоне' },
                    { code: 'Tajikistan', name: 'Таджикистан' },
                    { code: 'Thailand', name: 'Таиланд' },
                    { code: 'Tanzania', name: 'Танзания' },
                    { code: 'Togo', name: 'Того' },
                    { code: 'Tonga', name: 'Тонга' },
                    { code: 'Trinidad-and-Tobago', name: 'Тринидад и Тобаго' },
                    { code: 'Tuvalu', name: 'Тувалу' },
                    { code: 'Tunisia', name: 'Тунис' },
                    { code: 'Turkmenistan', name: 'Туркмения' },
                    { code: 'Turkey', name: 'Турция' },
                    { code: 'Uganda', name: 'Уганда' },
                    { code: 'Uzbekistan', name: 'Узбекистан' },
                    { code: 'Ukraine', name: 'Украина' },
                    { code: 'Uruguay', name: 'Уругвай' },
                    { code: 'Federated-States-of-Micronesia', name: 'Федеративные Штаты Микронезии' },
                    { code: 'Fiji', name: 'Фиджи' },
                    { code: 'Philippines', name: 'Филиппины' },
                    { code: 'Finland', name: 'Финляндия' },
                    { code: 'France', name: 'Франция' },
                    { code: 'Croatia', name: 'Хорватия' },
                    { code: 'Central-African-Republic', name: 'Центральноафриканская Республика' },
                    { code: 'Chad', name: 'Чад' },
                    { code: 'Montenegro', name: 'Черногория' },
                    { code: 'Czech', name: 'Чехия' },
                    { code: 'Chile', name: 'Чили' },
                    { code: 'Switzerland', name: 'Швейцария' },
                    { code: 'Sweden', name: 'Швеция' },
                    { code: 'Sri-Lanka', name: 'Шри-Ланка ' },
                    { code: 'Ecuador', name: 'Эквадор' },
                    { code: 'Equatorial-Guinea', name: 'Экваториальная Гвинея' },
                    { code: 'Eritrea', name: 'Эритрея' },
                    { code: 'Esvatini', name: 'Эсватини' },
                    { code: 'Estonia', name: 'Эстония' },
                    { code: 'Ethiopia', name: 'Эфиопия' },
                    { code: 'South-Africa', name: 'ЮАР' },
                    { code: 'South-Sudan', name: 'Южный Судан' },
                    { code: 'Jamaica', name: 'Ямайка' },
                    { code: 'Japan', name: 'Япония' }
                ];

                this.countryForDelivery = '';
                this.observe('active', this._onChangeCountry);
                this.observe('language', this._switchLanguage);
                this._switchLanguage();
            }

            _switchLanguage() {
                if (i18next.language) {
                    this.list = (i18next.language === 'ru') ? this.ruList : this.enList;
                    this.active = this.list[0].code;
                    // this._onChangeCountry();
                }
                return i18next.language;
            }

            _onChangeCountry() {
                const active = this.active;
                this.countryForDelivery = this._getNameCountry(this.active);
                if (active) {
                    this.onChange = this.countryForDelivery;
                } else {
                    this.active = this.list[0].code;
                    this.onChange = this._getNameCountry(this.active);
                }
            }

            _getNameCountry(codeCountry) {
                const selectedCountry = this.list.find(item => item.code === codeCountry);
                const searchedCountry = (selectedCountry) ? selectedCountry.name : this.list[0].name;
                return searchedCountry;
            }

        }

        return new ChangeCountry();
    };

    controller.$inject = ['Base'];

    angular.module('app.ui').component('wChangeCountry', {
        bindings: {
            onChange: '=',
            language: '='
        },
        templateUrl: 'modules/ui/directives/changeCountry/changeCountry.html',
        transclude: false,
        controller
    });
})();
